apiVersion: v2
name: magda-auth-arcgis
description: A Magda Authentication Plugin for ArcGIS Server
version: "2.0.0-alpha.0"
kubeVersion: ">= 1.14.0-0"
home: "https://github.com/magda-io/magda-auth-arcgis"
sources: [ "https://github.com/magda-io/magda-auth-arcgis" ]
dependencies:
  - name: magda-common
    version: "2.1.1"
    repository: "oci://ghcr.io/magda-io/charts"
